liberaforms/views/invite.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2021 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""


from flask import Blueprint, redirect, request
from flask import current_app, flash, g, url_for, jsonify
from flask_babel import gettext as _
import flask_login
from liberaforms.models.invite import Invite
from liberaforms.models.formuser import FormUser
from liberaforms.utils import auth

invite_bp = Blueprint('invite_bp', __name__)


@invite_bp.route('/invite/preview', methods=['POST'])
@auth.enabled_editor_required__json
def invite_preview():
    if "text" in request.form and request.form["text"]:
        return jsonify(
            text=Invite.parse_message(request.form["text"], replace_vars=False),
            preview=Invite.get_preview(request.form["text"])
        ), 200

    default_msg = Invite.default_message(
        flask_login.current_user.preferences['language']
    )
    return jsonify(text="", preview=Invite.get_preview(default_msg)), 200

liberaforms/views/site.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2020 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

import os
import json
import mimetypes
import markdown
import markupsafe
from feedgen.feed import FeedGenerator
from sqlalchemy.orm.attributes import flag_modified
from flask import g, request, render_template, redirect, Response
from flask import Blueprint, current_app, url_for
from flask import session, flash, jsonify
from jinja2 import Template
from flask_babel import gettext as _
from flask_babel import force_locale
import flask_login

from liberaforms.models.site import Site
from liberaforms.models.invite import Invite
from liberaforms.models.user import User
from liberaforms.models.form import Form
from liberaforms.models.consent import Consent
from liberaforms.models.schemas.consent import ConsentSchema
from liberaforms.models.formconsent import FormConsent
from liberaforms.domain.user import UserDomain
from liberaforms.domain.custom_text import CustomText
from liberaforms.utils import utils
from liberaforms.utils import auth
from liberaforms.utils import sanitizers
from liberaforms.utils import tokens
from liberaforms.utils import html_parser
from liberaforms.utils.chart_data import get_site_statistics
from liberaforms.utils.dispatcher import Dispatcher
from liberaforms.utils import wtf
from liberaforms.utils import i18n
from liberaforms.utils.inline_help import InlineHelp

# from pprint import pprint

site_bp = Blueprint('site_bp', __name__,
                    template_folder='../templates/site')


@site_bp.route('/site/recover-password', methods=['GET', 'POST'])
def recover_password():
    if flask_login.current_user.is_authenticated:
        flask_login.logout_user()
    wtform = wtf.GetEmail()
    if wtform.validate_on_submit():
        user = User.find(email=wtform.email.data, blocked=False)
        if user:
            user.save_token()
            Dispatcher().send_account_recovery(user)
        elif wtform.email.data == current_app.config['ROOT_USER']:
            # auto invite root user
            invite = Invite(email=wtform.email.data,
                            message="New root user",
                            token=tokens.create_token(),
                            role='admin',
                            invited_by_id=None)
            invite.save()
            return redirect(url_for('user_bp.create_new_user',
                                    invite=invite.token['token']))
        flash(_("We may have sent you an email"), 'info')
        return redirect(url_for('main_bp.index'))
    return render_template('user/recover-password.html', wtform=wtform)


@site_bp.route('/site/new-user-form', methods=['GET'])
@auth.enabled_admin_required
def new_user_form_preview():
    consents = ConsentSchema(
                many=True,
                only=('id', 'label', 'text', 'field_name', 'checkbox_label', 'required')
                ).dump(g.site.get_registration_consents())
    consent_library = ConsentSchema(many=True).dump(g.site.consents)
    return render_template('user/new-user.html',
                           wtform=wtf.NewUser(),
                           consents=consents,
                           consent_library=consent_library,
                           preview_only=True)


@site_bp.route('/site/new-user-form/enable-consent', methods=['POST'])
@auth.enabled_admin_required__json
def new_user_form_enable_consent():
    if not ('consent_id' in request.form and 'enable' in request.form):
        return jsonify("Not Acceptable"), 406
    consent_id = json.loads(request.form['consent_id'])
    enable = utils.str2bool(request.form['enable'])
    consent = Consent.find(id=consent_id, site_id=g.site.id)
    if not consent:
        return jsonify("Not found"), 404
    if consent.id in g.site.registration_consent and not enable:
        g.site.registration_consent.remove(consent.id)
    elif consent.id not in g.site.registration_consent and enable:
        g.site.registration_consent.append(consent.id)
    g.site.save()
    consents = ConsentSchema(
                many=True,
                only=('id', 'label', 'text', 'field_name', 'checkbox_label', 'required')
                ).dump(g.site.get_registration_consents())
    return jsonify(enabled_consents=consents), 200


# ## Site settings

@site_bp.route('/site/look-and-feel', methods=['GET'])
@auth.enabled_admin_required
def look_and_feel():
    wtcolorform = wtf.ChangeTheme()
    wtcolorform.primary_color.data = g.site.theme["primary_color"]
    wtcolorform.font_color.data = g.site.theme['navbar']['font_color']
    return render_template('site/look-and-feel.html',
                           wtcolorform=wtcolorform,
                           human_readable_bytes=utils.human_readable_bytes,
                           site=g.site)


@site_bp.route('/site/change-name', methods=['POST'])
@auth.enabled_admin_required
def change_name():
    if request.method == 'POST' and 'sitename' in request.form:
        name = sanitizers.remove_html_tags(request.form['sitename'])
        if name:
            g.site.name = name
            g.site.save()
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/change-icon', methods=['POST'])
@auth.enabled_admin_required
def change_icon():
    if not request.files['file']:
        flash(_("Required file is missing"), 'warning')
        return redirect(url_for('site_bp.look_and_feel'))
    file = request.files['file']
    if "image/" in file.content_type:
        try:
            g.site.change_favicon(file)
            flash(_("Logo changed OK. Refresh with <F5>"), 'success')
        except Exception as error:
            current_app.logger.error(error)
    else:
        flash(_("An image file is required"), 'warning')
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/reset-icon', methods=['GET'])
@auth.enabled_admin_required
def reset_icon():
    if g.site.reset_favicon():
        flash(_("Logo reset OK. Refresh with <F5>"), 'success')
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/change-theme', methods=['POST'])
@auth.enabled_admin_required
def change_theme():
    wtform = wtf.ChangeTheme()
    if wtform.validate_on_submit():
        g.site.theme["primary_color"] = wtform.primary_color.data
        g.site.theme['navbar']['font_color'] = wtform.font_color.data
        g.site.save()
        flash(_("Colors updated OK"), 'success')
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/new-user-language', methods=['GET', 'POST'])
@auth.enabled_admin_required
def set_new_user_language():
    if request.method == 'POST':
        if 'language' in request.form and \
          request.form['language'] in current_app.config['LANGUAGES']:
            g.site.newuser_language = request.form['language']
            g.site.save()
            flash(_("Language updated OK"), 'success')
            return redirect(url_for('admin_bp.admin_panel'))
    return render_template('new-user-language.html',
                           current_language=g.site.newuser_language)


@site_bp.route('/site/mimetypes', methods=['GET', 'POST'])
@auth.enabled_admin_required
def edit_mimetypes():
    wtform = wtf.FileExtensions()
    if wtform.validate_on_submit():
        mimetypes.init()
        updated_mimetypes = {"extensions": [], "mimetypes": []}
        extensions = wtform.extensions.data.splitlines()
        for extension in extensions:
            extension = extension.lower()
            if not extension:
                continue
            mime_type = mimetypes.types_map[f".{extension}"]
            if extension not in updated_mimetypes["extensions"]:
                updated_mimetypes["extensions"].append(extension)
                updated_mimetypes["mimetypes"].append(mime_type)
        g.site.mimetypes = updated_mimetypes
        g.site.save()
        flash(_("Enabled file extensions updated OK"), 'success')
    if request.method == 'GET':
        wtform.extensions.data = '\n'.join(g.site.mimetypes['extensions'])
    return render_template('edit-mimetypes.html', wtform=wtform)


@site_bp.route('/site/toggle-invitation-only', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_invitation_only():
    return jsonify(invite=g.site.toggle_invitation_only())


@site_bp.route('/site/toggle-newuser-uploads-default', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_newuser_uploads_default():
    return jsonify(uploads=g.site.toggle_newuser_uploads_default())

# ## i18n texts


@site_bp.route('/site/custom-translations', methods=['GET'])
@auth.enabled_admin_required
def custom_languages():
    lang_codes = os.path.join(current_app.config['ASSETS_DIR'], 'language_codes.json')
    with open(lang_codes, 'r', encoding="utf-8") as all_languages:
        languages = json.load(all_languages)
    return render_template('site/custom-translations.html',
                           custom_languages=i18n.get_custom_languages(),
                           all_languages=languages)


@site_bp.route('/site/add-custom-language', methods=['POST'])
@auth.enabled_admin_required__json
def add_custom_language():
    if not ("lang_code" in request.form and request.form["lang_code"]):
        return jsonify("Not acceptable"), 406
    lang_code = request.form["lang_code"]
    if lang_code in g.site.custom_languages:
        return jsonify("Not acceptable"), 406
    lang_codes = os.path.join(current_app.config['ASSETS_DIR'], 'language_codes.json')
    with open(lang_codes, 'r', encoding="utf-8") as all_languages:
        languages = json.load(all_languages)
    selected_lang = [d for d in languages if d['value'] == lang_code]
    if not selected_lang:
        return jsonify("Not acceptable"), 406
    g.site.custom_languages.append(lang_code)
    g.site.save()
    enabled = [d for d in languages if d['value'] in g.site.custom_languages]

liberaforms/templates/site/custom-texts.html
{% extends "base-backend.html" %}
{% block content %}

<!-- custom_texts_page -->

{% set multilanguage = custom_languages|length > 1 %}


<div class="ds-narrow-container">
  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">
      <a href="{{url_for('admin_bp.admin_panel')}}" arial-label="return"><i data-feather="arrow-left"></i></a>
      <h1>{{ _('Custom texts') }}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <p class="mb-0">
        {{ _("Edit these texts to suit your site.") }}
      </p>
      {% if multilanguage %}
      <p class="mb-0">
        {% set languages = [] %}
        {% for language in custom_languages %}
          {% set languages = languages.append(language.name) %}
        {% endfor -%}
        {{ _("Languages") }}:
        <a href="{{ url_for('site_bp.custom_languages') }}">{{ ', '.join(languages) }}</a>
      </p>
      {% endif %}
    </div>
  </div>

  <div class="grid mt-3 ds-wrapper-white">
    <div class="g-col-12">
      <ul class="ds-list-group">
        <li>
          <span>
            {# i18n: Option in admin settings about changing instance welcoming text #}
            {{ _("Front page text") }}
          </span>
          <span class="text-nowrap">
            {% if multilanguage %}
              {% set blurbs = CustomText("frontpage-blurb").get_completion() %}
              {% if blurbs.completed %}
                <span class="badge rounded-pill bg-success">{{blurbs.stats}}</span>
              {% else %}
                <span class="badge rounded-pill bg-secondary">{{blurbs.stats}}</span>
              {% endif %}
            {% endif %}
            <a href="{{url_for('site_bp.edit_blurb')}}" class="ds-link-contain-icon">
            {{ _("Edit") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
          </span>
        </li>
        <li>
          {# i18n: Option in admin setting to edit the Resources menu #}
          <span>{{ _("Resources menu") }}:
            <strong>
            {% if g.site.resources_menu['enabled'] %}
            {{ _("Enabled") }}
            {% else %}
            {{ _("Disabled") }}
            {% endif %}
            </strong>
          </span>
          <span class="text-nowrap">
            {% if multilanguage %}
              {% set resources_menus = CustomText("resources-menu").get_completion() %}
              {% if resources_menus.completed %}
                <span class="badge rounded-pill bg-success">{{resources_menus.stats}}</span>
              {% else %}
                <span class="badge rounded-pill bg-secondary">{{resources_menus.stats}}</span>
              {% endif %}
            {% endif %}
            <a href="{{url_for('site_bp.edit_resources_menu')}}" class="ds-link-contain-icon">
            {{ _("Edit") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
          </span>
        </li>
        <li>
          <span>{{ _("Other information") }}</span>
          <span class="text-nowrap">
            {% if multilanguage %}
              {% set other_infos = CustomText("other-information").get_completion() %}
              {% if other_infos.completed %}
                <span class="badge rounded-pill bg-success">{{other_infos.stats}}</span>
              {% else %}
                <span class="badge rounded-pill bg-secondary">{{other_infos.stats}}</span>
              {% endif %}
            {% endif %}
            <a href="{{url_for('site_bp.edit_contact_info')}}" class="ds-link-contain-icon">
            {{ _("Edit") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
          </span>
        </li>
        <li>
          {# i18n: Option in admin setting to edit the Data privacy wizard disclaimer #}
          <span>{{ _("Wizard disclaimer") }}</span>
          <span class="text-nowrap">
            {% if multilanguage %}
              {% set disclaimers = CustomText("wizard-disclaimer").get_completion() %}
              {% if disclaimers.completed %}
                <span class="badge rounded-pill bg-success">{{disclaimers.stats}}</span>
              {% else %}
                <span class="badge rounded-pill bg-secondary">{{disclaimers.stats}}</span>
              {% endif %}
            {% endif %}
            <a href="{{url_for('site_bp.edit_wizard_disclaimer')}}" class="ds-link-contain-icon">
            {{ _("Edit") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
          </span>
        </li>
        <li>
          {# i18n: Option in admin setting to edit the User invitation text #}
          <span>{{ _("User invitation template") }}</span>
          <span class="text-nowrap">
            {% if multilanguage %}
              {% set invitation_texts = CustomText("invitation-text").get_completion() %}
              {% if invitation_texts.completed %}
                <span class="badge rounded-pill bg-success">{{invitation_texts.stats}}</span>
              {% else %}
                <span class="badge rounded-pill bg-secondary">{{invitation_texts.stats}}</span>
              {% endif %}
            {% endif %}
            <a href="{{url_for('site_bp.invitation_template')}}" class="ds-link-contain-icon">
            {{ _("Edit") }} <i data-feather="chevron-right" aria-hidden="true"></i></a></span>
        </li>
        <li>
          <span>
            {# i18n: Option in admin settings about changing the message displayed when a new form is created #}
            {{ _("New form message") }}:
            <strong>
            {% if g.site.new_form_msg['enabled'] %}
            {{ _("Enabled") }}
            {% else %}
            {{ _("Disabled") }}
            {% endif %}
            </strong>
          </span>
          <span class="text-nowrap">
            {% if multilanguage %}
              {% set new_form_msgs = CustomText("new-form-msg").get_completion() %}
              {% if new_form_msgs.completed %}
                <span class="badge rounded-pill bg-success">{{new_form_msgs.stats}}</span>
              {% else %}
                <span class="badge rounded-pill bg-secondary">{{new_form_msgs.stats}}</span>
              {% endif %}
            {% endif %}
            <a href="{{url_for('site_bp.new_form_msg')}}" class="ds-link-contain-icon">
            {{ _("Edit") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
          </span>
        </li>
    </div>
  </div>
</div>

<script>
const inline_help_file_name = "site_customtexts.j2.md";

</script>

{% endblock %}

liberaforms/templates/site/custom-translations.html
{% extends "base-backend.html" %}
{% block content %}

<!-- site_custom_languages_page -->

<script src="/static/vendor/bs5-autocomplete/autocomplete.js"></script>

<div class="ds-narrow-container">

  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">
      <a href="{{url_for('admin_bp.admin_panel')}}" arial-label="return"><i data-feather="arrow-left"></i></a>
      <h1>{{ _("Custom translations") }}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <p class="mb-0">
        {{ _("Define the languages used to translate custom texts.") }}
        <a href="#" onclick="toggleInlineHelp('site_customlanguages.j2.md')">{{ _("Learn more") }}</a>
      </p>
    </div>
  </div>

  <div class="grid mt-3 ds-wrapper-white">
    <div class="g-col-12">
      <ul id="enabled_language_list" class="ds-list-group"></ul>
    </div>
  </div>

  <div class="grid mt-4 ds-wrapper-white">
    <div class="g-col-12">
      <label class="form-label">{{_("Add a language")}}</label>
      <div class="input-group mb-4">
        <input type="text" class="form-control" id="new-language" placeholder="{{_('Start typing...')}}" autocomplete="off">
      </div>
    </div>
  </div>

</div>

<script>
const inline_help_file_name = "site_customlanguages.j2.md";
var custom_languages = {{custom_languages|tojson}};
var default_language = "{{g.site.language}}"
$(function() {
  updateDisplay();
  $('#enabled_language_list').on("click", ".language-radio", function(){
    setDefaultLanguage($(this).val())
  });
});
const field = document.getElementById('new-language');
const ac = new Autocomplete(field, {
    data: {{all_languages|tojson}},
    label: "name",
    maximumItems: 5,
    threshold: 1,
    onSelectItem: ({label, value}) => {
      $.ajax({
          url : "{{url_for('site_bp.add_custom_language')}}",
          type: "POST",
          data : {
            lang_code: value,
          },
          dataType: "json",
          beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
          },
          success: function(data, textStatus, jqXHR)
          {
            custom_languages = data.custom_languages
            updateDisplay();
            $("#new-language").val("")
          }
      });
    }
});
function removeLang(lang_code) {
  $.ajax({
      url : "{{url_for('site_bp.remove_custom_language')}}",
      type: "POST",
      data : {
        lang_code: lang_code,
      },
      dataType: "json",
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      },
      success: function(data, textStatus, jqXHR)
      {
        custom_languages = data.custom_languages
        updateDisplay();
        $("#new-language").val("")
      }
  });
}
function setDefaultLanguage(lang_code) {
  $.ajax({
      url : "{{url_for('site_bp.set_default_custom_language')}}",
      type: "POST",
      data : {
        lang_code: lang_code,
      },
      dataType: "json",
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      },
      success: function(data, textStatus, jqXHR)
      {
        custom_languages = data.custom_languages
        default_language = data.default_language
        updateDisplay();
      }
  });
}
function updateDisplay() {
  $('#enabled_language_list').html("")
  custom_languages.forEach(function(language) {
    var template = lang_template.replace(/%lang_code%/g, language.value)
                                .replace(/%lang_name%/g, language.name);
    let is_default = language.value == default_language
    template = template.replace(/%disabled%/, is_default ? "disabled":"")
    template = template.replace(/%checked%/, is_default ? "checked":"")
    template = template.replace(/%default%/, is_default ? "({{_('default')}})":"")
    $('#enabled_language_list').append(template);
  })
}
const lang_template = `
<li>
  <span>
    <input id="%lang_code%-lang" type="radio" %checked% class="language-radio" value="%lang_code%" arial-label="{{_('Default language')}} %lang_name%" />
    <label for="%lang_code%-lang">%lang_name% %default%
  </span>
  <span>
    <button %disabled% class="btn btn-sm btn-danger" onclick="removeLang('%lang_code%')">{{_("Remove")}}</button>
  </span>
</li>
`
</script>

{% endblock %}

liberaforms/templates/site/edit-consent.html
{% extends "base-backend.html" %}
{% block content %}

<!-- site_edit_consent_page -->

<div class="ds-narrow-container">

  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">
      <a href="{{url_for('consent_bp.list_site_data_consents')}}" arial-label="return"><i data-feather="arrow-left"></i></a>
      <h1>{% if consent.id %}{{ _("Edit privacy statement") }}{% else %}{{ _("New privacy statement") }}{% endif %}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <div id="consent_usage" class="d-flex justify-content-between align-items-center">
        {% if consent.id %}
          {% include('consent/partials/usage.html') %}
        {% else %}
          <span>{{ _("This statement can be attached to your forms and edited as needed.") }}</span>
        {% endif %}
      </div>
    </div>
  </div>

  {% with scope="site" %}
    {% include 'consent/partials/edit-consent.html' %}
  {% endwith %}

</div>

<script>
const inline_help_file_name = "site_dataconsent_edit.j2.md";
</script>

{% endblock %}

liberaforms/templates/site/invitation-template.html
{% extends "base-backend.html" %}
{% block content %}

<!-- edit_invitation_text_page -->

<div class="ds-narrow-container">

  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">
      <a href="{{ url_for('site_bp.custom_texts')}}" arial-label="return"><i data-feather="arrow-left"></i></a>
      <h1>{{ _("Invitation template") }}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <p class="mb-0">{{ _("This template can be edited when inviting a new user.") }}</p>
    </div>
  </div>

  <form name="inviteText" method="post" class="mt-3">
    <div class="grid ds-wrapper-white">
      <div class="g-col-12">
        {{ wtform.csrf_token }}
        {% if g.site.custom_languages|length > 1 %}
        <div class="mb-4">
          {{ wtform.language.label(for="language", class_="form-label") }}
          {{ wtform.language(id="language", class_="form-select", onchange="changeLanguage()") }}
        </div>
        {% else %}
          <input id="language" type="hidden" name="language" value="{{g.site.language}}" />
        {% endif %}
        <div class="">
        {{ wtform.text.label(for="template-text", class_="form-label") }}
        {{ wtform.text(id="template-text",
                       class_="form-control mw-100",
                       rows="9")}}
        {% for error in wtform.text.errors %}
          <span class="wtf-error ds-error-message">{{ error }}</span>
        {% endfor %}
        </div>

        <div class="mt-4">
          <input class="btn btn-outline-primary" type="button" onclick="showPreview()" value="{{ _('Preview') }}" />
          <input class="btn btn-primary" type="submit" value="{{ _('Save') }}" />
        </div>
      </div>
    </div>
  </form>

  <div class="grid">
    <div class="g-col-12">
      <div id="preview" class="g-col-12 mt-4 p-3 text-bg-light" style="display:none">
        <div id="preview-text"><div>
      </div>
    </div>
  </div>

</div>

<script>
const inline_help_file_name = "site_invitationtemplate.j2.md";
const placeholders = {{ placeholders | tojson }}
var texts = {{ texts | tojson }}
var preview_cache = {}
var lang_code = null

function showPreview() {
  getPreview().then(function() {
    $('#preview-text').html(preview_cache[lang_code]);
    $('#preview').show()
    $('html, body').animate({
        scrollTop: $("#preview").offset().top -200
    }, 250);
  });
}
const textarea = document.getElementById('template-text')
$(function() {
  changeLanguage();
  $("form[name=inviteText]").focusin(function() {
    if (!$("input[type=submit]").is(":focus")) {
      $('#preview').hide()
      delete preview_cache[lang_code];
    }
  });
});
function changeLanguage() {
  lang_code = $('#language').val()
  setMessageValue()
  $('#preview').hide()
}
function setMessageValue() {
  if (texts[lang_code]) {
    $("#template-text").val(texts[lang_code])
  } else {
    $("#template-text").val(placeholders[lang_code])
  }
}
function getPreview() {
  return new Promise(function(resolve, reject) {
    if (Object.keys(preview_cache).includes(lang_code) && preview_cache[lang_code] !== "") {
      resolve()
      return
    }
    $.ajax({
      url : "{{ url_for('invite_bp.invite_preview') }}",
      type: "POST",
      dataType: "json",
      data: {"language": lang_code, "text": $("#template-text").val()},
      beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
      },
      success: function(data, textStatus, jqXHR)
      {
        if (data.preview) {
          preview_cache[lang_code] = data.preview
          resolve()
        }
      }
    });
  });
}
</script>

{% endblock %}