liberaforms/models/formuser.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2021 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

from datetime import datetime, timezone
from sqlalchemy.orm.attributes import flag_modified
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP
from sqlalchemy.ext.mutable import MutableDict
from flask import url_for
from liberaforms import db
from liberaforms.utils.database import CRUD
from liberaforms.utils import utils

class FormUser(db.Model, CRUD):
    """FormUser model definition."""

    __tablename__ = "form_users"
    id = db.Column(db.Integer, primary_key=True, index=True, unique=True)
    created = db.Column(TIMESTAMP, nullable=False)
    form_id = db.Column(db.Integer,
                        db.ForeignKey('forms.id', ondelete="CASCADE"),
                        nullable=False)
    user_id = db.Column(db.Integer,
                        db.ForeignKey('users.id', ondelete="CASCADE"),
                        nullable=False)
    is_editor = db.Column(db.Boolean, default=False)
    notifications = db.Column(MutableDict.as_mutable(JSONB), nullable=False)
    ui_preferences = db.Column(MutableDict.as_mutable(JSONB), nullable=False)
    field_index = db.Column(JSONB, nullable=True)
    order_by = db.Column(db.String, nullable=True)  # data_display preference
    ascending = db.Column(db.Boolean, default=True)  # data_display preference
    e2ee_ciphered_key_backup = db.Column(MutableDict.as_mutable(JSONB), nullable=False)
    user = db.relationship("User", viewonly=True)
    form = db.relationship("Form", viewonly=True)

    def __init__(self, **kwargs):
        """Create a new FormUser object."""
        self.created = datetime.now(timezone.utc)
        self.form_id = kwargs['form'].id
        self.user_id = kwargs['user'].id
        self.notifications = kwargs['user'].new_form_notifications()
        self.is_editor = kwargs['is_editor']
        self.ui_preferences = FormUser.default_ui_prefs()
        self.e2ee_ciphered_key_backup = kwargs.get('e2ee_ciphered_key_backup', {})

    def __str__(self) -> str:
        """Use for debugging."""
        return utils.print_obj_values(self)

    @classmethod
    def find(cls, **kwargs):
        """Return first FormUser filtered by kwargs."""
        return cls.find_all(**kwargs).first()

    @classmethod
    def find_all(cls, **kwargs):
        """Return all FormUsers filtered by kwargs."""
        return cls.query.filter_by(**kwargs)

    @staticmethod
    def default_ui_prefs() -> dict:
        """Toggle blocks of info."""
        return {
            'introduction_text': True,  # show config block
            'form_preview': True,  # show config block
            'data_consents': True,  # show config block
            'after_submit_text': True,  # show config block
            'chrono_answers': True,  # show chronological answer submissions
            'landing_page': '',
        }

    @staticmethod
    def avaiable_landing_pages() -> list:
        return ["", "details", "expiration", "answers", "grid", "cards", "graphs", "map"]

    def get_ui_preference(self, pref):
        return self.ui_preferences[pref] if pref in self.ui_preferences else False

    def save_ui_preference(self, key, value):
        self.ui_preferences[key] = value
        flag_modified(self, "ui_preferences")
        self.save()

    def get_landing_page(self) -> str:
        if "landing_page" not in self.ui_preferences:
            return url_for('form_bp.inspect_form', form_id=self.form_id)
        pref = self.ui_preferences["landing_page"]
        if pref == "details":
            return url_for('form_bp.form_details', form_id=self.form_id)
        if pref.startswith("answers"):
            return url_for('answers_bp.list_answers', form_id=self.form_id)
        if pref == "expiration":
            return url_for('form_bp.expiration', form_id=self.form_id)
        return url_for('form_bp.inspect_form', form_id=self.form_id)

    def toggle_expiration_notification(self) -> bool:
        """Enable/disable expiration notification."""
        self.notifications['expiredForm'] = not self.notifications['expiredForm']
        self.save()
        return self.notifications['expiredForm']

    def toggle_new_answer_notification(self) -> bool:
        """Enable/disable new answer notification."""
        self.notifications['newAnswer'] = not self.notifications['newAnswer']
        self.save()
        return self.notifications['newAnswer']

    def get_field_index_preference(self) -> list:
        """Return a User's field_index order preference."""
        return self.field_index

    def save_field_index_preference(self, field_index:list) -> None:
        """Save a User's field_index order preference."""
        self.field_index = field_index
        self.save()

    def get_order_by_field(self) -> str:
        """User's "order answers by field" preference.

        Returns a field name.
        """
        return self.order_by

    def save_order_by(self, field_name:str) -> None:
        """Save a User's "order answers by field" preference."""
        self.order_by = field_name
        self.save()

    def toggle_ascending_order(self) -> bool:
        """Toggle User's ascending order preference."""
        self.ascending = not self.ascending
        self.save()
        return self.ascending

    def get_map_preferences(self) -> dict:
        if "map" in self.ui_preferences:
            return self.ui_preferences["map"]
        map_fields = self.form.get_map_fields()
        if map_fields:
            return {
                "center": map_fields[0]["centerPoint"].replace(' ', '')
                                                      .split(','),
                "zoom": map_fields[0]["zoom"]
            }
        return {}

    def get_form_role(self) -> str:
        if self.form.author_id == self.user.id:
            return 'author'
        return 'editor' if self.is_editor else 'reader'

    def is_e2ee_enabled(self) -> bool:
        # from pprint import pprint
        # pprint({
        #     'form': self.form.e2ee_public_key['fingerprint'],
        #     'ciphered_form': self.e2ee_ciphered_key_backup['form_key_fingerprint'],
        #     'user': self.user.e2ee_public_key['fingerprint'],
        #     'cyphered_user': self.e2ee_ciphered_key_backup['user_key_fingerprint'],
        # })
        return (
            self.form.is_e2ee_enabled() and
            self.user.is_e2ee_enabled() and
            self.e2ee_ciphered_key_backup and
            self.e2ee_ciphered_key_backup['form_key_fingerprint'] ==
            self.form.e2ee_public_key['fingerprint'] and
            self.e2ee_ciphered_key_backup['user_key_fingerprint'] ==
            self.user.e2ee_public_key['fingerprint']
        )

liberaforms/views/form.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2023 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

import json
import datetime
from urllib.parse import urlparse
import markupsafe
from sqlalchemy.orm.attributes import flag_modified
from flask import current_app, Blueprint
from flask import g, request, render_template, redirect, url_for, jsonify
from flask import flash, send_file
from flask_babel import ngettext, gettext as _
import flask_login

from liberaforms.domain import form as form_domain
from liberaforms.domain.custom_text import CustomText
from liberaforms.models.form import Form
from liberaforms.models.invite import Invite
from liberaforms.models.schemas.invite import InviteSchema
from liberaforms.models.schemas.consent import ConsentSchema
from liberaforms.models.schemas.formuser import FormUserSchema
from liberaforms.models.user import User
from liberaforms.models.formuser import FormUser
from liberaforms.models.formauth import FormAuth
from liberaforms.form_templates import form_templates
from liberaforms.utils import utils
from liberaforms.utils import tokens
from liberaforms.utils import auth
from liberaforms.utils import form_helper
from liberaforms.utils import sanitizers
from liberaforms.utils import validators
from liberaforms.utils import html_parser
from liberaforms.utils import ldap
from liberaforms.utils.dispatcher.dispatcher import Dispatcher
from liberaforms.utils import wtf
from liberaforms.utils import i18n

# from pprint import pprint

form_bp = Blueprint('form_bp', __name__,
                    template_folder='../templates/form')


@form_bp.route('/forms', methods=['GET'])
@flask_login.login_required
@auth.enabled_user_required
def my_forms():
    #user_forms = FormUser.find_all(user_id=flask_login.current_user.id)
    #if flask_login.current_user.is_guest():
    #    if user_forms.count() == 0:
    #        return redirect(url_for('user_bp.user_settings'))
    #    if user_forms.count() == 1:
    #        granted_form = user_forms[0].form
    #        return redirect(url_for('answers_bp.list_answers', form_id=granted_form.id))
    return render_template('my-forms.html')


@form_bp.route('/form/new', methods=['GET', 'POST'])
@form_bp.route('/form/new/template/<int:template_id>', methods=['GET', 'POST'])
@form_bp.route('/form/new/duplicate/<int:duplicate_id>', methods=['GET', 'POST'])
@auth.enabled_editor_required
def create_new_form(template_id=None, duplicate_id=None):
    wtform = wtf.NewForm()
    wtform.is_e2ee.render_kw = {
        'disabled': current_app.config['E2EE_MODE'].mode == 'REQUIRED',
    }
    if template_id:
        template = next((sub for sub in form_templates.templates if sub['id'] == template_id), None)
        if not template:
            flash(_("Cannot find that form template"), 'error')
            return redirect(url_for('form_bp.list_templates'))
    else:
        template = None
    if duplicate_id:
        duplicate_form = Form.find(id=duplicate_id)
        if not duplicate_form:
            flash(_("Cannot find the form to duplicate"), 'error')
            return redirect(url_for('form_bp.my_forms'))
        if not (flask_login.current_user.is_admin() or
                FormUser.find(form_id=duplicate_form.id,
                              user_id=flask_login.current_user.id,
                              is_editor=True)):
            flash(_("You can't duplicate that form"), 'info')
            return redirect(url_for('form_bp.my_forms'))
    else:
        duplicate_form = None
    if wtform.validate_on_submit():
        if not flask_login.current_user.can_create_forms():
            return redirect(url_for('form_bp.create_new_form'))
        is_e2ee = True if current_app.config['E2EE_MODE'].is_required else wtform.is_e2ee.data
        if is_e2ee and not flask_login.current_user.e2ee_public_key:
            return redirect(url_for('form_bp.create_new_form'))
        kwargs = {
            'name': wtform.name.data,
            'slug': wtform.slug.data,
            'is_e2ee': is_e2ee
        }
        if template:
            markdown = i18n.lazytext_to_serializable(template['introduction_md'])
            structure = form_helper.repair_form_structure(template['structure'])
            template_args = {
                "introduction_text": {
                             "markdown": markdown,
                             "html": sanitizers.markdown_to_html(markdown)},
                "structure": i18n.lazytext_to_serializable(structure)
            }
            kwargs = {**kwargs, **template_args}
        try:
            form = Form(flask_login.current_user, **kwargs)
            if duplicate_form:
                excluded_props = [
                    '_sa_instance_state',
                    'id',
                    'created',
                    'author_id',
                    'name',
                    'slug',
                    'enabled',
                    'is_e2ee',
                    'e2ee_public_key',
                    'published_cnt',
                    'edit_mode',
                ]
                for prop in vars(duplicate_form):
                    if prop not in excluded_props:
                        setattr(form, prop, getattr(duplicate_form, prop))
            form.save()
        except Exception as error:
            current_app.logger.error(error)
            flash(_("Failed to create form"), 'warning')
            return redirect(url_for('form_bp.create_new_form'))
        FormUser(form=form, user=flask_login.current_user, is_editor=True).save()
        current_app.logger.info(f'FORM - User "{form.author.username}" created form {form.id}, "{form.slug}"')
        form.add_log(_("Form created"))
        Dispatcher().send_new_form_notification(form)  # notify admins
        if g.site.new_form_msg["enabled"]:
            messages = g.site.new_form_msg["languages"]
            #flash(markupsafe.Markup(i18n.get_best_language_value(messages)), 'info')
            flash(markupsafe.Markup(CustomText("new-form-msg").get_text()), 'info')

        else:
            flash(_("New form created ok"), 'success')
        return redirect(url_for('form_bp.inspect_form', form_id=form.id))
    form_source_msg = None
    if template:
        form_source_msg = _('You are creating a copy of the template "%(name)s"',
                            name=template["name"])
    if duplicate_form:
        form_source_msg = _('You are creating a copy of the form "%(name)s"',
                            name=duplicate_form.name)
    wtform.is_e2ee.data = current_app.config['E2EE_MODE'].default_form_value
    return render_template('new-form.html',
                           wtform=wtform,
                           form_source_msg=form_source_msg)


@form_bp.route('/forms/check-slug-availability', methods=['POST'])
@auth.enabled_editor_required__json
def is_slug_available():
    if 'slug' in request.form and request.form['slug']:
        slug = request.form['slug']
    else:
        return jsonify(slug="",
                       available=False,
                       error_msg=_("A slug is required")), 200
    # we return a sanitized slug as a suggestion to the user.
    slug = sanitizers.sanitize_slug(slug)
    if len(slug) < 5 or len(slug) > 50:
        return jsonify(slug=slug,
                       available=False,
                       error_msg=_("Min. 5 and max. 100 characters")), 200
    if not Form.is_slug_available(slug):
        return jsonify(slug=slug,
                       available=False,
                       error_msg=_("This URL is not available. Try another!")), 200
    return jsonify(slug=slug, available=True), 200


@form_bp.route('/form/<int:form_id>', methods=['GET'])
@auth.enabled_user_required
@auth.instantiate_form(allow_admin=False, allow_reader=True)
@form_domain.expire_on_date_condition
def inspect_form(form_id, **kwargs):
    form = kwargs["form"]
    if kwargs["is_form_reader"]:
        return redirect(url_for('answers_bp.list_answers', form_id=form.id))
    kwargs["form_user"].save_ui_preference('landing_page', 'config')
    consents = ConsentSchema(many=True).dump(form.get_consents())
    return render_template('form-configuration.html',
                           form=form,
                           form_user=kwargs["form_user"],
                           goto=request.args.get("goto", None),
                           consents=consents,
                           upload_media_form=wtf.UploadMedia(),
                           human_readable_bytes=utils.human_readable_bytes)


@form_bp.route('/form/<int:form_id>/options', methods=['GET'])
@auth.enabled_user_required
@auth.instantiate_form(allow_admin=False)
@form_domain.expire_on_date_condition
def form_details(form_id, **kwargs):
    form = kwargs["form"]
    kwargs["form_user"].save_ui_preference('landing_page', 'details')
    return render_template('form-options.html',
                           form=form,
                           FormUser=FormUser,
                           form_user=kwargs["form_user"],
                           is_form_editor=kwargs["is_form_editor"],
                           Invite=Invite,
                           human_readable_bytes=utils.human_readable_bytes,
                           status_badges=form_helper.status_badges)


@form_bp.route('/form/<int:form_id>/edit', methods=['GET'])
@auth.enabled_user_required
@auth.instantiate_form(allow_admin=False)
def edit_form(form_id, **kwargs):
    form = kwargs['form']
    if form.edit_mode and form.edit_mode['editor_id'] != flask_login.current_user.id:
        flash(_("The form is being edited by %(email)s",
                email=form.edit_mode["editor_email"]), 'warning')
        return redirect(url_for('form_bp.form_details', form_id=form.id))
    editing_preview = bool(request.args.get('preview') and form.preview)
    if editing_preview:
        preview_structure = form.preview["structure"]
        form.preview = {}
        form.save()

liberaforms/views/invite.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2021 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""


from flask import Blueprint, redirect, request
from flask import current_app, flash, g, url_for, jsonify
from flask_babel import gettext as _
import flask_login
from liberaforms.models.invite import Invite
from liberaforms.models.formuser import FormUser
from liberaforms.utils import auth

invite_bp = Blueprint('invite_bp', __name__)


@invite_bp.route('/invite/preview', methods=['POST'])
@auth.enabled_editor_required__json
def invite_preview():
    if "text" in request.form and request.form["text"]:
        return jsonify(
            text=Invite.parse_message(request.form["text"], replace_vars=False),
            preview=Invite.get_preview(request.form["text"])
        ), 200

    default_msg = Invite.default_message(
        flask_login.current_user.preferences['language']
    )
    return jsonify(text="", preview=Invite.get_preview(default_msg)), 200

liberaforms/templates/form/invite-user.html
{% extends "base-backend.html" %}
{% block content %}

<!-- form_invite_page -->

{% with active_item="settings",
        sub_option=True,
        form=granted_form %}
  {% include 'form/partials/form-context.html' %}
{% endwith %}

<div class="ds-narrow-container mt-2">

  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">

    {% if grant_as == 'editor' %}
      <a href="{{url_for('form_bp.form_editors', form_id=granted_form.id)}}" arial-label="return"><i data-feather="arrow-left"></i></a>
    {% else %}
      <a href="{{url_for('form_bp.form_readers', form_id=granted_form.id)}}" arial-label="return"><i data-feather="arrow-left"></i></a>
    {% endif %}
      <h1>
        {{ _("Send an invitation") }}
      </h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      {% if grant_as == 'editor' %}
        <p class="mb-0">{{ _("Grant full acces to your form.") }}</p>
      {% else %}
        <p class="mb-0">{{ _("Grant read-only access to the collected answers") }}.</p>
      {% endif %}
    </div>
  </div>

  <div class="grid mt-3 ds-wrapper-white">
    <div class="g-col-12">
      <form name="inviteUserForm" method="POST" autocomplete="off">
        {{ wtform.csrf_token }}
        <div class="form-group mt-2">
          {{ wtform.email.label(for="new-invite-email",
                                class_="form-label") }}
          {{ wtform.email(id="new-invite-email",
                          class_="form-control",
                          placeholder=_("person@example.com")) }}
          {% for error in wtform.email.errors %}
            <span class="wtf-error ds-error-message">{{ error }}</span>
          {% endfor %}
        </div>

        <div class="mt-4">
          <button id="preview-message-btn" class="btn btn-sm btn-outline-secondary" type="button" onclick="toggleEditor()">{{ _("Edit message")}}</button>
          <button id="reset-button" class="btn btn-sm btn-outline-secondary" type="button" onclick="resetMessage()" style="display:none">{{ _("Use default")}}</button>
        </div>
        <div id="message-editor" class="form-group mt-3" style="display:none">
          {{ wtform.message.label(for="new-invite-message",
                                  class_="form-label") }}
          {{ wtform.message(id="new-invite-message",
                          class_="form-control",
                          rows=7) }}
          {% for error in wtform.message.errors %}
            <span class="wtf-error ds-error-message">{{ error }}</span>
          {% endfor %}
        </div>

        <div id="preview" class="mt-4 p-3 text-bg-light" style="display:none">
          <div id="preview-message"></div>
        </div>

        <div class="mt-4">
          {# i18n: Button to send new user invitation message via email #}
          <input class="btn btn-primary" type="submit" value="{{ _('Send email') }}">
        </div>
      </form>
    </div>
  </div>

</div>

<script>
const inline_help_file_name = "form_invitation.j2.md";
const default_message = `{{ default_message }}`
var message = `{{ wtform.message.data }}`
var preview = `{{ preview | safe }}`

$("form[name=inviteUserForm]").parsley().on('field:validate', function(field) {
  $(field.element).closest('.form-group').find('.wtf-error').remove()
})

$(function() {
  {% if wtform.message.errors %}
    preview = ""
    showEditor()
  {% else %}
    showPreview()
  {% endif %}
});
function showPreview() {
  $("#preview-message-btn").html("{{ _('Edit message') }}")
  $("#preview-message-btn").removeClass('btn-primary').addClass('btn-outline-secondary')
  $("#message-editor").hide()
  $("#reset-button").hide()
  $('#preview-message').html(preview);
  $("#preview").show()
  $("form").find(":submit").prop('disabled', false)
}
function showEditor() {
  $("#preview-message-btn").html("{{ _('Set message') }}")
  $("#preview-message-btn").addClass('btn-primary').removeClass('btn-outline-secondary')
  $("#preview").hide()
  $("#new-invite-message").val(message)
  $("#message-editor").show()
  $("#new-invite-message").focus()
  $("#reset-button").show()
  $("form").find(":submit").prop('disabled', true)
}
function resetMessage() {
  $("#new-invite-message").val(default_message)
}
function toggleEditor() {
  if ($("#preview").is(':visible')) {
    showEditor()
  } else {
    $.ajax({
      url : "{{ url_for('invite_bp.invite_preview') }}",
      type: "POST",
      dataType: "json",
      data: {"text": $("#new-invite-message").val()},
      beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
      },
      success: function(data, textStatus, jqXHR)
      {
        if (Object.keys(data).includes("text") && data.preview) {
          message = data.text
          preview = data.preview
          showPreview()
        }
      }
    });
  }
}
</script>

{% endblock %}

liberaforms/templates/form/look-and-feel.html
{% extends "base-frontend.html" %}
{% block content %}

{# Future idea: Fonts https://www.design-research.be/by-womxn/ #}

<!-- form_style_page -->

{% if not previewing_edition %}
  {% with modal_id="insert_background_image_modal",
          form_id="insert_background_image_form",
          modal_title=_("Background image") %}
    {% include 'common/insert-image-modal.html' %}
  {% endwith %}
  {% with modal_id="insert_header_image_modal",
          form_id="insert_header_image_form",
          modal_title=_("Featured image") %}
    {% include 'common/insert-image-modal.html' %}
  {% endwith %}
  {% with form_id=form.id %}
    {% include 'form/modals/color-selector-modals.html' %}
  {% endwith %}
{% endif %}


<div class="grid align-items-start fixed-top ds-header-title-with-button">
  {% if previewing_edition %}
  <div class="g-col-2"></div>
  <div class="g-col-10">
    <nav class="navbar-expand-lg ds-accions-look-and-feel">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#formActions" aria-controls="formActions" aria-expanded="false" aria-label="Toggle navigation">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
      </button>
      <div class="navbar-collapse collapse mt-1 gap-2" id="formActions">
        <form class="d-inline" action="{{url_for('form_bp.cancel_edition', form_id=form.id, killed=False|int)}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button type="submit" class="btn btn-sm btn-outline-primary">
            {{ _("Cancel") }}
          </button>
        </form>
        <button type="button" class="btn btn-sm btn-outline-primary" onclick="document.location='{{url_for('form_bp.edit_form', form_id=form.id, preview=True)}}'">
          {{ _("Edit again") }}
        </button>
        <form class="d-inline" action="{{url_for('form_bp.save_form', form_id=form.id, preview=True)}}" method="POST" >
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button type="submit" class="btn btn-sm btn-primary">
            {{ _("Save changes") }}
          </button>
        </form>
      </div>
    </nav>
  </div>
  {% else %}
  <div class="g-col-7">
    <nav class="navbar-expand-lg ds-accions-look-and-feel">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#styleActions" aria-controls="styleActions" aria-expanded="false" aria-label="Toggle style options">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-feather"><path d="M20.24 12.24a6 6 0 0 0-8.49-8.49L5 10.5V19h8.5z"></path><line x1="16" y1="8" x2="2" y2="22"></line><line x1="17.5" y1="15" x2="9" y2="15"></line></svg>
      </button>
      <div class="navbar-collapse collapse mt-1 gap-2" id="styleActions">
        <button class="btn btn-outline-primary btn-sm" type="button" onclick="$('#insert_header_image_modal').modal('show'); return false;">{{ _("Featured image") }}</button>
        <button class="btn btn-outline-primary btn-sm" type="button" onclick="$('#font_color_selector_modal').modal('show'); return false;">{{ _("Font color") }}</button>
        <button class="btn btn-outline-primary btn-sm" type="button" onclick="$('#background_color_selector_modal').modal('show'); return false;">{{ _("Background color") }}</button>
        <button class="btn btn-outline-primary btn-sm" type="button" onclick="$('#insert_background_image_modal').modal('show'); return false;">{{ _("Background image") }}</button>
        <button class="btn btn-outline-dark btn-sm" type="button" onclick="javascript:clearStyle(); this.blur()">{{ _("Clear") }}</button>
      </div>
    </nav>
  </div>

  <div class="g-col-5">
    <button class="btn btn-primary btn-sm mt-1" type="button" onclick="document.location='{{go_back_url}}'">{{ _("Go back") }}</button>
  </div>
  {% endif %}
</div>

<div class="grid mt-5 pt-sm-5">
  <div class="g-col-12 g-col-sm-10 g-start-sm-2 g-col-md-8 g-start-md-3 g-col-lg-6 g-start-lg-4 g-col-xxl-4 g-start-xxl-5">
  {% with preview_only=True %}
    {% include 'public_form/partials/view-form.html' %}
  {% endwith %}
  </div>
</div>

{% if not previewing_edition %}
<script>
{% include 'form/js/form_style.js' %}

// triggered at common/insert-image-modal.html
$(document).on("add_header_image", function(event) {
  $('#insert_header_image_modal').modal('hide');
  let initial_image_src = $("#header_image").attr("src")
  let image_url = $("#insert_header_image_form").find('#image_url').val().trim()
  $("#header_image").prop("src", image_url)
  $("#header_image").show()
  $.ajax({
    url : "{{ url_for('form_style_bp.set_header_image', form_id=form.id) }}",
    type: "POST",
    dataType: "json",
    data: { "image_url": image_url },
    beforeSend: function(xhr, settings) {
      if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    },
    error: function(data, textStatus, jqXHR)
    {
      $("#header_image").attr("src", initial_image_src)
      if (! initial_image_src) {
        $("#header_image").hide()
      }
    }
  });
});

</script>
{% endif %}

{% endblock %}

liberaforms/templates/form/my-forms.html
{% extends "base-backend.html" %}
{% block content %}

<!-- my_forms_page -->

<div class="grid ds-header-title">
  <div class="g-col-12">
    <h1>{{ _("My forms") }}</h1>
  </div>
</div>

<div class="grid mt-3">
  <div class="g-col-12">
    <p class="mb-0">{{ _("The forms you have created and those shared with you by other users.") }}
  </div>
</div>

<div class="ds-wrapper-white mt-3">
  <div vue-component="data-display"
        data-endpoint="/data-display/my-forms/{{current_user.id}}"
        data-ui_language="{{ g.language }}"
        data-csrf_token="{{ csrf_token() }}">
  </div>
  <div vue-component="items-renderer"></div>
</div>

<script src="{{config['DATA_DISPLAY_BASE_URL']}}/data-display.js"></script>
<script src="{{config['DATA_DISPLAY_BASE_URL']}}/items-renderer.js"></script>

<script>
const inline_help_file_name = "forms.j2.md";
</script>

{% endblock %}